### PR TITLE
Added "query" function with some errors

### PR DESCRIPTION
**Pull request by lcqsigi**
The raise NotFound statement decreases the nosetests to 94%. Please check.

### CODE REVIEW

**Comment by lcqsigi** [comment]
(venv) vagrant@ubuntu:/vagrant$ nosetests                  

Test Cases for InventoryItem Model
- Create an inventory item and assert that it exists
- Ensure InventoryItem.delete() behaves as expected
- Test deserialization of an InventoryItem
- Test deserialization of an InventoryItem with bad data
- Test deserialization of an InventoryItem with missing data
- Find or return 404 NOT found
- Ensure string representation of an InventoryItem is correct
- Test serialization of an InventoryItem

InventoryItem Server Tests
- Ensure a 400 is returned if the request data is bad
- Create a new Inventory item
- Delete an inventory item
- Ensure a 404 is returned if a DELETE is sent for a nonexistant item
- Test the index page
        Return some useful information when root url is requested
- Ensure a 405 is returned if a non-GET request is sent to /
- Ensure a 415 is raised if an unsupported media type is used
- Update in stock status for an inventory item

----------------------------------------------------------------------
XML: /vagrant/unittests.xml
Name                        Stmts   Miss  Cover   Missing
---------------------------------------------------------
service/__init__.py            26      4    85%   34, 44-47
service/error_handlers.py      32      3    91%   75-77
service/models.py              70      1    99%   83
service/routes.py              52      4    92%   45-49, 91
service/status.py              46      0   100%
---------------------------------------------------------
TOTAL                         226     12    95%
----------------------------------------------------------------------
Ran 16 tests in 0.952s

**Comment by cslecrone** [comment]
You'll probably need two test cases here. The first should be able to find the item by its ID, the second should search for a nonexistent item and then raise a 404.

Additionally, you're missing the ability to be able to query by `SKU`, `stock level`, `restock level`, `restock amount` or `in_stock`. A query endpoint usually supports multiple fields. The code in `lab-flask-tdd` should be able to help you with both test coverage as well as the additional functionality. 

Finally, you have a merge conflict since @avllee21 landed changes last night. You'll need to resolve that so we can merge your changes when they're ready.

**Comment by lcqsigi** [comment]
@cslecrone: we can probably close **this pull** and focus on the other **pull** that I just created. The **new pull** works as expected. I can add the `SKU`, `stock level`, etc. changes later in another **pull** request.

**Comment by cslecrone** [comment]
Yeah, just close it out.

**Pull request closed without merging**
